run:
  timeout: 10m
  go: "1.23.8"
  skip-dirs:
    - "third_party"
    - "vendor"
    - "generated"

linters:
  enable-all: true
  disable:
    - structcheck  # deprecated
    - varcheck     # deprecated  
    - deadcode     # deprecated
    - scopelint    # deprecated

linters-settings:
  wrapcheck:
    ignoreSigs:
      - "github.com/nephio-project/porch/internal/kpt/errors.E"
      - "fmt.Errorf"
      - "errors.Wrap"
      - "errors.Wrapf"
      - "github.com/pkg/errors.Wrap"
      - "github.com/pkg/errors.Wrapf" 